destination:
  name: in-cluster
  namespace: infisical
manifests: true
helm:
  repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
  targetRevision: 1.8.0
  chart: infisical-standalone
syncPolicy:
  automated:
    enabled: true
    prune: false
    selfHeal: false
  syncOptions:
    - CreateNamespace=true
    - PruneLast=true
