apiVersion: v1
stringData:
  AUTH_SECRET: QF9bk5yPmhdgnsJ6Xcj98VguMkzCdnNS2xWUvIbF0NQ=
  ENCRYPTION_KEY: TCOeL+7q6lfk0R/ifVtVsPrMOrgSaJhw/A0CWmnShkI=
  SITE_URL: https://infisical.172.19.0.50.nip.io
  DB_CONNECTION_URI: postgresql://infisical:changeme@infisical-postgres-rw:5432/infisical
kind: Secret
metadata:
  name: infisical-secrets
