apiVersion: v1
data:
  AUTH_SECRET: RDVHblZuOHVZRUpPZDRkbjdGRHA0V0ZNVC9aYzkyTkFheG9KMHVLdEttND0=
  ENCRYPTION_KEY: MTViNzliYzU2ZGMyZTEyNDhiMzk2NGI0YWYzYmVkOTM=
  SITE_URL: aHR0cDovL2luZmlzaWNhbC4xNzIuMTkuMC41MC5uaXAuaW8=
kind: Secret
metadata:
  name: infisical-secrets
  namespace: infisical
