apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  {{- if .Values.serviceName }}
  name: "{{.Values.serviceName}}"
  {{- else }}
  {{- printf "serviceName must be defined" | fail }}
  {{- end }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: "{{.Values.repoURL}}"
        revision: "{{.Values.revision}}"
        directories:
          - path: "{{.Values.servicesPath}}/{{.Values.serviceName}}/env"
  template: {}
