serviceName: ""
repoURL: https://github.com/tonychg/kubedev.git
revision: master
project: default
destination: {}
servicesPath: services
manifests: false
annotations: {}
sources: []
helm: {}
# targetRevision: ""
# repoURL: ""
# chart: ""
# releaseName: ""
# skipCrds: false
syncPolicy: {}
