destination:
  namespace: haproxy-controller
helm:
  repoURL: https://haproxytech.github.io/helm-charts
  targetRevision: {{ haproxy.revision }}
  chart: kubernetes-ingress
syncPolicy:
  automated:
    enabled: true
    prune: false
    selfHeal: false
  syncOptions:
    - CreateNamespace=true
    - PruneLast=true
