destination:
  name: in-cluster
  namespace: haproxy-controller
helm:
  repoURL: https://haproxytech.github.io/helm-charts
  targetRevision: 1.44.0
  chart: kubernetes-ingress
syncPolicy:
  automated:
    enabled: true
    prune: true
    selfHeal: false
  syncOptions:
    - CreateNamespace=true
    - PruneLast=true
