manifests: true
destination:
  name: in-cluster
  namespace: kube-system
helm:
  repoURL: https://helm.cilium.io
  targetRevision: 1.19.1
  chart: cilium
syncPolicy:
  automated:
    enabled: true
    prune: false
    selfHeal: false
  syncOptions:
    - Validate=true
    - CreateNamespace=true
ignoreDifferences:
  - group: '*'
    kind: Secret
    name: cilium-ca
    namespace: kube-system
    jsonPointers:
      - /data/ca.crt
      - /data/ca.key
  - group: '*'
    kind: Secret
    name: hubble-server-certs
    namespace: kube-system
    jsonPointers:
      - /data/ca.crt
      - /data/tls.crt
      - /data/tls.key
