apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: master
      ref: app
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.5.3
      helm:
        skipCrds: false
        valueFiles:
          - $app/services/argocd/values.yaml
    - repoURL: https://argoproj.github.io/argo-helm
      path: argocd/services.yaml
      directory:
        recurse: false
