apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  sources:
    - repoURL: &repoURL https://github.com/tonychg/kubedev.git
      targetRevision: &targetRevision master
      ref: app
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.5.3
      helm:
        skipCrds: false
        valueFiles:
          - $app/services/argocd/values.yaml
    - repoURL: *repoURL
      targetRevision: *targetRevision
      path: argocd
      directory:
        include: services.yaml
        recurse: false
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - ServerSideApply=true
