apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-services
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/tonychg/kubedev.git
        revision: master
        requeueAfterSeconds: 15
        files:
          - path: "services/*/service.yaml"
        values:
          serviceName: '{{ .path.basenameNormalized }}'
  syncPolicy:
    # Create and Update but not Delete
    applicationsSync: create-update
    # Delete resources on deletion
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: "service-{{.values.serviceName}}"
    spec:
      destination:
        name: in-cluster
        namespace: argocd
      project: default
      sources:
        - repoURL: https://github.com/tonychg/kubedev.git
          targetRevision: master
          ref: service
        - repoURL: https://github.com/tonychg/kubedev.git
          path: charts/argocd-service
          targetRevision: master
          helm:
            valuesObject:
              serviceName: "{{.values.serviceName}}"
            valueFiles:
              - $service/services/{{.values.serviceName}}/service.yaml
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
