global:
  domain: argocd.172.19.0.50.nip.io

certificate:
  enabled: true

server:
  ingress:
    enabled: true
    ingressClassName: haproxy
    annotations:
      haproxy.org/ssl-passthrough: "true"
      haproxy.org/ssl-redirect: "false"
    tls: true
