destination:
  name: in-cluster
  namespace: cnpg-system
helm:
  repoURL: https://cloudnative-pg.github.io/charts
  targetRevision: 0.27.0
  chart: cloudnative-pg
syncPolicy:
  automated:
    enabled: true
    prune: false
    selfHeal: false
  syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
    - PruneLast=true
