destination:
  namespace: monitoring
helm:
  repoURL: https://prometheus-community.github.io/helm-charts
  targetRevision: 83.7.0
  chart: kube-prometheus-stack
syncPolicy:
  automated:
    enabled: true
    prune: false
    selfHeal: false
  syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - ServerSideApply=true
ignoreDifferences:
  - group: '*'
    kind: Secret
    name: monitoring-grafana
    namespace: monitoring
    jsonPointers:
      - /data/admin-password
  - group: apps
    kind: Deployment
    name: monitoring-grafana
    namespace: monitoring
    jsonPointers:
      - /spec/template/metadata/annotations/checksum~1secret
